### PR TITLE
doxygen changes

### LINKED ISSUE #73: update doxyfile to doxygen-1.9.1, turn on WARN_AS_ERROR and other settings
update doxyfile to doxygen-1.9.1, turn on WARN_AS_ERROR and other settings

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #31 
Fixes #73

Doxygen improvements.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
There are more changes to come in future PRs, but this gets the sp library off to a good start.

In this PR I:
* update the Doxyfile.in - @AlexanderRichert-NOAA notice the settings, which should be turned on everywhere. These include WARN_AS_ERROR (which causes documentation build to fail if there is a documentation warning), and the REFERENCES settings (which automatically generate the list of functions called by and calling every function, so that we don't have to keep track of that ourselves in the docs.)
* Clean up the user_guide.md file - this is the top-layer of documentation.
* Improve the documentation of a bunch of code files.
* Add documentation to two files that had none. They were not being included in the docs because they did not have the @file tag.

Some things to notice about the formatting:
* Doxygen formats all white-space, so we don't bother aligning things with extra spaces. One space is plenty.
* Author and optional date tag at the end of every file block and function/subroutine block. If there is just one subroutine in the file, these will be the same, but put it in both places, because when a new subroutine is added, we will know who added the file, and who wrote both subroutines.
* I generally move program history into the file-level description. It is formatted as a nice doxygen table.
* I lower-case the text, but not necessarily the parameter descriptions or equations. I don't want to change values of equations, and since the code is capitalized I don't want to change parameters.
* File blocks need a @breif tag. Subroutine/function blocks don't need the tag - they will use the first sentence as the brief description for the function. So it should be exactly that.

**Comment by edwardhartnett** [comment]
@EricEngle-NOAA and @GeorgeGayno-NOAA (and anyone else) - can you provide ANY guidance about what the functions in fftpack.f are doing?

This is literally my current documentation:

```
C> @file
C> @brief fftpack.

C> dcrft
C>
C> @param init
C> @param x
C> @param ldx
C> @param y
C> @param ldy
C> @param n
C> @param m
C> @param isign
C> @param scale
C> @param  table
C> @param n1
C> @param wrk
C> @param n2
C> @param z
C> @param nz

```

The file is in code review for this PR. If you have any ideas, enter them as comments in the review.

**Comment by EricEngle-NOAA** [comment]
Looks like fftpack.F is a concatenation of the [fftpack library](https://netlib.org/fftpack/).  The doc page does contain some information about purpose of subroutines/functions and description of arguments.

**Comment by jbathegit** [comment]
It looks like `@brief` tags are still missing from spanaly.f, ncpus.F, spgradq.f, and spwget.f.

I noticed that you also removed the variable types (INTEGER, REAL, etc.) from the definitions in the `@param` tags.  I realize Doxygen figures those out automatically when it generates the HTML documentation, but IMHO it's still useful to have those types explicitly documented in the source as well, because believe it or not some people do still read docblocks in the actual source code ;-)

Otherwise it looks OK to me.

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Comment by edwardhartnett** [comment]
We remove the variable types because doxygen figures them out.

The reasons:
1 - Doxygen is always right, we may not be.
2 - We seek to minimize the number of characters needed to express the documentation.

Just as we do not tolerate extra, unused variables in our programs, we should not tolerate unnecessary duplication of information, which adds work and presents additional opportunities for human error.

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA I have fixed the missing @brief tags in the next PR. Thanks for catching that...

**Comment by edwardhartnett** [comment]
@EricEngle-NOAA thanks, that helps a lot. I have added that to the docs. Unfortunately the fftpack code is also completely undocumented. But at least we have something...

**Comment by jbathegit** [comment]
> @AlexanderRichert-NOAA I have fixed the missing @brief tags in the next PR. Thanks for catching that...

It was actually me who pointed that out earlier, but no worries and glad to hear it will be fixed in a later PR ;-)

**Pull request merged**
