### PR TITLE
Add Intel LLVM support

### LINKED ISSUE #113: Add Intel LLVM support
Working on https://github.com/NOAA-EMC/NCEPLIBS-ip/issues/142, might as well update sp while we're at it.

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
Adding Intel LLVM support.

Tested on Hera with Intel OneAPI 2023.1.0. No compiler warnings, and no apparent issues with compiler flags.

Fixes https://github.com/NOAA-EMC/NCEPLIBS-sp/issues/113

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett if this looks good I'll update the required test settings.

**Review by EricEngle-NOAA — APPROVED** [review]

**Comment by edwardhartnett** [comment]
Looks fine to me!

**Review by edwardhartnett — APPROVED** [review]
Awesome we should do this on all active NCEPLIBS...

**Comment by edwardhartnett** [comment]
Can you add this to the g2, g2tmpl, grib_utils, and prod_utils repos as well?

**Pull request merged**
