### PR TITLE
Use a Github Action matrix to build for multiple OS's and OpenMP

### LINKED ISSUE #53: add macos build to github actions?
Should we add the macos build?

I'm pretty sure there is a way to add it to an existing workflow without adding a new workflow for it. But I've never tried...

### PR DESCRIPTION
**Pull request by kgerheiser**
Fixes #53 and also adds the OpenMP ON/OFF into a single workflow.

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]
Awesome! I'm sure we will find many other places to use this.

**Comment by kgerheiser** [comment]
Hmmm, something about changing the workflow name causes one of the checks to hang and also prevents merging

**Comment by kgerheiser** [comment]
I had to uncheck the old Action and select the new ones in the repository settings

**Comment by edwardhartnett** [comment]
Hmm, thanks for telling me, I'll remember that tip...

**Pull request merged**
