### PR TITLE
PR for shared object lib builds

### PR DESCRIPTION
**Pull request by EricEngle-NOAA**
PR for shared object library building. #67

### CODE REVIEW

**Comment by edwardhartnett** [comment]
In the macos build, try changing FC to gfortran-12.

See https://github.com/ufs-community/UFS_UTILS/issues/712

**Comment by EricEngle-NOAA** [comment]
Made some updates for the cmake config to ensure the GNU OpenMP library is being appropriately linked to static and shared libs.

I split the macOS and Linux GCC actions into 2 separate actions.  I am using gfortran-11 in both given the documentation for the macos-latest and ubuntu-latest runners.

I removed the combined action.  Apologies in advance if I was not supposed to do that.

**Review by edwardhartnett — APPROVED** [review]

**Comment by EricEngle-NOAA** [comment]
Thanks, @edwardhartnett for approving.  I will make similar changes to the cmake config for NCEPLIBS-ip and submit PR there.

**Comment by edwardhartnett** [comment]
Instead of adding workflows, make changes to the Linux and MacOS workflows.

Here is how you should use these workflows:
* developer - Only run once. Do all the memory checking, warning checks, documentation build, address santizer, code coverage report, here, and nowhere else.
* Linux - test everything here, all combinations of options and versions. (If that becomes too much, I split this workflow into Linux_versions and Linux_options, as in the g2c project.)
* MacOS - test with all options turned on, but don't test all combinations of options and versions here. Just pick a one or a few cases. Mac testing is very slow on GitHub.
* Intel - similar to Linux but for Intel. Slower than Linux runs, so I also try to limit testing of many combinations in the Intel workflow.

So in your case, add the extra testing options (shared on/off) to Linux, MacOS, and Intel. If you really want to add testing for different versions of the GNU compilers, do that just in Linux.

**Review by edwardhartnett — CHANGES_REQUESTED** [review]
Make changes to existing workflows instead of adding new one...

**Review by edwardhartnett — APPROVED** [review]

**Comment by EricEngle-NOAA** [comment]
@edwardhartnett just wondering when we can expect a release for sp that contains shared-object library support.

**Comment by edwardhartnett** [comment]
Do we need a realease?

We can do one if needed...

**Comment by edwardhartnett** [comment]
OK we are using option BUILD_SHARED_LIBS. Is that correct? What is typically used with CMake?

I would have thought something like ENABLE_SHARED would be more commonly used...

**Comment by EricEngle-NOAA** [comment]
A patch release would be great.  This way we can reference what version (and newer) of NCEPLIBS-sp to use for shared library support.  The same will hold true for NCEPLIBS-ip.

I found both BUILD_SHARED_LIBS and ENABLE_SHARED options in my research on the topic.  The top-level Cmake config for netcdf-c uses BUILD_SHARED_LIBS

https://github.com/Unidata/netcdf-c/blob/0fc2c817b247ab6a862127b7d069c16b2c29a93c/CMakeLists.txt#L239

**Pull request merged**
